version: '3'
services:
  hk-nginx:
   container_name: hk-nginx2
   image: nginx:1.13
   restart: always
   ports:
   - 80:80
   - 443:443
   volumes:
   - ./nginx/conf.d:/etc/nginx/conf.d
   networks:
   - frontend
   



  app:
    restart: always
    build: ./IPSpec
    working_dir: /IPSpec
    volumes:
      - ./IPSpec:/IPSpec
      - ~/.m2:/root/.m2
    expose:
      - "8080"
    command: mvn clean spring-boot:run
    depends_on:
      - db1
      - db2
    networks:
      - backend
      - frontend
    
      
  

 
  db1:
    container_name: neo4j-ips2019
    image: neo4j:latest
    ports:
      - '7474:7474'
      - '7473:7473'
      - '7687:7687'
    environment:
      - NEO4J_AUTH=neo4j/admin
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4J_dbms_shell_enabled=true
      - NEO4j_dbms.memory.pagecache.size=5G
    networks:
      - backend
    volumes:
      - ./IPSpec/neo4jdata:/import
    
    
      
  db2:
    container_name: clickhouse-ips
    image: yandex/clickhouse-server:latest
    ports:
      - "8123:8123"
      - "9000:9000"  
    networks:
      - backend
    
networks:
    backend:
    frontend:
        
      

   

